### ISSUE TITLE
`vsk.penWidth()` seems to be broken

### ISSUE THREAD

**Issue by ademuri** [abey79/vsketch#416] opened 2023-12-25 18:00 UTC
I'm running vsk version 1.0.0, on Ubuntu 20.04.

It appears that calling `vsk.penWidth()` does not work. I tried using it in a simple sketch, but calling it with various values did not change anything. Setting the default pen width in the menu in the vsk gui worked fine.

For a reproducible test case, I loaded the `shape_basic` example, which calls `vsk.penWidth("2mm", 3)`. This also does not produce any discernible change, either in `vsk run` or `vsk save`.

I've attached exported svgs, using like: ![sketch_shape_basic_liked_1](https://github.com/abey79/vsketch/assets/3051618/61319cb7-2672-4a60-b77c-49d93e70c539)

and `vsk save`:
![sketch_shape_basic_vsk_save](https://github.com/abey79/vsketch/assets/3051618/f8ba2291-4e4b-4df4-81d3-666ff72bd4da)

**Comment by abey79** [comment] 2024-01-07 08:56
I can reproduce. It seems that the `Override` setting is broken: the path width is overridden regardless of the `Override` setting in the viewer.

**Comment by abey79** [comment] 2024-01-08 11:10
Nvm. I just never vsketch's `penWidth` to vpype's metadata (which was introduced later on). `vsk.penWidth` is currently used for fill hatching and other, but not displayed. This is basically a duplicate of #205

**Closed** 2024-01-08 11:33 UTC
